# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /blog/:title/


# Setup
title:               Brandon Walsh
tagline:
description:         "Head of Student Programs at the Scholars' Lab in the UVA Library"
url: http://walshbr.com
baseurl:             ''

# About/contact
author:
  name:              Brandon Walsh
  url:               https://twitter.com/mdo
  email:             walsh@virginia.edu

# Custom vars
version:             1.0.0


plugins_dir: ./_plugins
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
paginate: 1
paginate_path: "page:num"
category_dir: 'categories'

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
